# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: the-time

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test:coverage
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main
      - name: Build
        run: npm run build:pub
      - name: Build types
        run: npm run build:types
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH}}
